export const monkQuotes = [
    "Silence is the language of strength; learn to speak it.",
    "The mind becomes calm when the heart stops arguing with reality.",
    "Discipline is choosing what matters over what feels good.",
    "A peaceful life begins with a peaceful morning.",
    "Your next level is hidden behind your daily habits.",
    "Stillness is not empty; it is full of answers.",
    "Do not chase respect. Live in a way that makes it arrive on its own.",
    "Small daily improvements carve the path to mastery.",
    "Where your attention goes, your life follows.",
    "The greatest battles are fought within.",
    "Let go of what weighs you down; carry only what builds you up.",
    "You do not need more time; you need more focus.",
    "Your thoughts are seeds. Choose carefully what you plant.",
    "Peace comes when you stop wishing for a different past.",
    "What you avoid controls you.",
    "Master your mornings, and the day becomes your servant.",
    "Happiness grows in the soil of gratitude.",
    "A sharp mind is built from quiet hours.",
    "Wisdom begins when the ego ends.",
    "Discipline is freedom disguised as effort.",
    "What you practice in private becomes your power in public.",
    "You cannot calm the storm, but you can calm yourself.",
    "Focus turns ordinary days into extraordinary progress.",
    "Consistency is stronger than intensity.",
    "Nothing changes until your standards do.",
    "The quieter you become, the more you hear your purpose.",
    "Be patient with your journey; even mountains grow slowly.",
    "A pure heart sees clearly.",
    "When you detach, you begin to understand.",
    "Control your reactions; that is true power.",
    "Choose the path that makes you proud, not comfortable.",
    "A busy mind cannot be a wise mind.",
    "Growth often feels like discomfort; embrace it.",
    "The person you become is built from the habits you repeat.",
    "Let your actions show your values.",
    "Protect your peace like it is treasure—because it is.",
    "Change your environment and your mind will follow.",
    "Give energy only to what you want to grow.",
    "Maturity is learning to pause before responding.",
    "Do not compare journeys; every soul has its own speed.",
    "Simple lives are powerful lives.",
    "Learn to be alone without feeling lonely.",
    "When you stop rushing, life shows its beauty.",
    "A clear purpose removes a thousand distractions.",
    "Failure is a teacher dressed in disappointment.",
    "Walk slowly, but never backwards.",
    "The more you learn, the less you need to speak.",
    "Heal, not to forget, but to understand.",
    "True wealth is a calm mind.",
    "Stop seeking permission to become better.",
    "Energy flows where attention stays.",
    "Courage is doing the right thing even when no one sees.",
    "A peaceful space creates a peaceful mind.",
    "Greatness hides inside small daily routines.",
    "Speak less. Observe more.",
    "To grow, you must outgrow.",
    "Your future depends on the discipline you practice today.",
    "Nothing changes without your decision.",
    "Let go of the need to win every argument.",
    "Live slowly enough to feel your life.",
    "A steady mind is a strong mind.",
    "Your best teacher is your last mistake.",
    "Seek progress, not perfection.",
    "Everything is training the mind.",
    "You become powerful when you stop reacting.",
    "Rest is a discipline too.",
    "Simplicity reveals truth.",
    "Let your presence be stronger than your words.",
    "The world becomes quieter when you stop seeking noise.",
    "A routine is a staircase to your highest self.",
    "Your peace does not depend on others.",
    "The more you carry, the slower you walk—release the unnecessary.",
    "Change happens when excuses end.",
    "What you repeat today becomes your identity tomorrow.",
    "Patience is the companion of wisdom.",
    "A clear mind creates a clear life.",
    "Live with intention, not impulse.",
    "Do not rush healing; some lessons need time.",
    "Your life is shaped by what you tolerate.",
    "Every sunrise is a chance to begin again.",
    "Let gratitude be your daily discipline.",
    "A strong spirit is quiet, not loud.",
    "Protect your focus from cheap distractions.",
    "Growth feels uncomfortable because you're becoming someone new.",
    "You cannot control the wind, but you can shape your sails.",
    "A disciplined life becomes a beautiful life.",
    "Conquer your mind, and the world follows.",
    "The greatest progress happens in silence.",
    "What you hold onto holds you back.",
    "Learn to enjoy your own company.",
    "Thoughts become habits; habits become destiny.",
    "A wise person listens before speaking.",
    "Every day is a chance to rewrite your life.",
    "Choose meaning over comfort.",
    "If you master one habit, master consistency.",
    "Your peace is your real home.",
    "Do not fear slow progress; fear standing still.",
    "When you simplify, you strengthen.",
    "Let your life be guided by purpose, not pressure.",
    "Become someone your future self will thank."
];

export function getRandomQuote(): string {
    return monkQuotes[Math.floor(Math.random() * monkQuotes.length)];
}
